---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Environment'
Parameters:
  Stage:
    Type: String
    AllowedValues:
    - prod
    - verify
  VPCId:
    Type: String
  Subnets:
    Type: CommaDelimitedList
  GitHubRepo:
    Type: String

Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'ec2.amazonaws.com'
          Action: 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
      - !Ref Role
  Environment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName:
      EnvironmentName: !Sub ${GitHubRepo}-us-west-2-${Stage}-cf
      SolutionStackName: '64bit Amazon Linux 2016.09 v2.3.3 running PHP 7.0'
      OptionSettings:
      - Namespace: 'aws:autoscaling:launchconfiguration'
        OptionName: 'IamInstanceProfile'
        Value: !Ref InstanceProfile
      - OptionName: VPCId
        ResourceName: AWSEBSecurityGroup
        Namespace: "aws:ec2:vpc"
        Value: !Ref VPCId
      - OptionName: ELBSubnets
        Namespace: "aws:ec2:vpc"
        Value: !Join [ ",", !Ref Subnets ]
      - OptionName: Subnets
        ResourceName: AWSEBAutoScalingGroup
        Namespace: "aws:ec2:vpc"
        Value: !Join [ ",", !Ref Subnets ]

Outputs:
  EnvironmentName:
    Value: !Ref Environment
  EndpointURL:
    Value: !Sub '${Environment.EndpointURL}'
